### ISSUE TITLE
Bug：demo切换键盘的问题

### ISSUE THREAD

**Issue by MooYoo** [YuAo/WUEmoticonsKeyboard#14]
你好，我下载了demo，运行后，发现有一个问题。

第一次点击Swith Keyboard的时候，表情键盘能弹出来。
再次点击Swith Keyboard的时候，整个键盘隐藏了。

我查看了代码，再次点击Swith Keyboard应该是切换到系统默认的键盘，但是demo中再次点击Swith Keyboard却是隐藏键盘，这是哪里出了问题呢？

**Comment by YuAo** [comment]
你在真机上测试了吗？模拟器的软键盘是可以隐藏的。
